from pathlib import Path
path = Path('app/routes/mqtt_routes.py')
text = path.read_text(encoding='utf-8')
start = text.index('                        # START')
end = text.index('                except Exception as job_err:')
indent = ' ' * 24
L = []
add = L.append
add(indent + '# Hilfsfunktionen fuer Slot-/Spulen-Tracking')
add(indent + 'def _calc_usage(spool, start_remain, end_remain, start_total_len):')
add(indent + '    if start_remain is None or end_remain is None:')
add(indent + '        return 0.0, 0.0')
add(indent + '    used_percent = max(0.0, float(start_remain) - float(end_remain))')
add(indent + '    used_mm = (used_percent / 100.0) * float(start_total_len) if start_total_len else 0.0')
add(indent + '    used_g = 0.0')
add(indent + '    if spool and spool.weight_full is not None and spool.weight_empty is not None:')
add(indent + '        used_g = (used_percent / 100.0) * (float(spool.weight_full) - float(spool.weight_empty))')
add(indent + '    return used_mm, used_g')
add('')
add(indent + 'def _finalize_current(info_local):')
add(indent + "    if info_local.get('slot') is None:")
add(indent + '        return None')
add(indent + "    sp = session.get(Spool, info_local.get('spool_id')) if info_local.get('spool_id') else None")
add(indent + '    used_mm, used_g = _calc_usage(')
add(indent + '        sp,')
add(indent + "        info_local.get('start_remain'),")
add(indent + "        info_local.get('last_remain'),")
add(indent + "        info_local.get('start_total_len'),")
add(indent + '    )')
add(indent + '    return {')
add(indent + "        'spool_id': info_local.get('spool_id'),")
add(indent + "        'slot': info_local.get('slot'),")
add(indent + "        'used_mm': used_mm,")
add(indent + "        'used_g': used_g,")
add(indent + '    }')
add('')
add(indent + 'def _set_current_slot(info_local, new_slot, job_obj):')
add(indent + '    tray_new = _find_tray(ams_data if isinstance(ams_data, list) else [], new_slot)')
add(indent + "    start_rem = tray_new.get('remain') if tray_new else None")
add(indent + "    total_len = tray_new.get('total_len') if tray_new else None")
add(indent + '    spool_obj = match_spool(new_slot, tray_new) or create_spool_from_tray(new_slot, tray_new)')
add(indent + '    if not job_obj.spool_id and spool_obj:')
add(indent + '        job_obj.spool_id = spool_obj.id')
add(indent + '    info_local.update(')
add(indent + '        {')
add(indent + "            'slot': new_slot,")
add(indent + "            'spool_id': spool_obj.id if spool_obj else None,")
add(indent + "            'start_remain': start_rem,")
add(indent + "            'start_total_len': total_len,")
add(indent + "            'last_remain': start_rem,")
add(indent + '        }')
add(indent + '    )')
add('')
add(indent + '# START: Slot/Spulen-Init')
add(indent + "if gstate.upper() in ('RUNNING', 'START', 'PRINTING') and printer_id:")
add(indent + '    if serial_from_topic and serial_from_topic not in active_jobs:')
add(indent + "        slot = job_data.get('tray_target') if isinstance(job_data, dict) else None")
add(indent + '        if slot is None:')
add(indent + "            slot = job_data.get('tray_current') if isinstance(job_data, dict) else None")
add(indent + '        slot_int = int(slot) if slot is not None else None')
add(indent + '        tray_info = _find_tray(ams_data if isinstance(ams_data, list) else [], slot_int)')
add(indent + '        raw_name = None')
add(indent + '        if isinstance(job_data, dict):')
add(indent + "            raw_name = job_data.get('subtask_name')")
add(indent + '        if not raw_name and isinstance(parsed_json, dict):')
add(indent + "            raw_name = parsed_json.get('subtask_name')")
add(indent + '        if not raw_name and isinstance(parsed_json, dict):')
add(indent + "            raw_name = parsed_json.get('gcode_file') or parsed_json.get('file')")
add(indent + "        if raw_name and '/' in raw_name:")
add(indent + "            raw_name = raw_name.split('/')[-1]")
add(indent + '        spool_obj = match_spool(slot_int, tray_info) or create_spool_from_tray(slot_int, tray_info)')
add(indent + '        job = Job(')
add(indent + '            printer_id=printer_id,')
add(indent + '            spool_id=spool_obj.id if spool_obj else None,')
add(indent + "            name=raw_name or 'Unnamed Job',")
add(indent + '            filament_used_mm=0,')
add(indent + '            filament_used_g=0,')
add(indent + '        )')
add(indent + '        session.add(job)')
add(indent + '        session.commit()')
add(indent + '        session.refresh(job)')
add(indent + '        active_jobs[serial_from_topic] = {')
add(indent + "            'job_id': job.id,")
add(indent + "            'slot': slot_int,")
add(indent + "            'spool_id': spool_obj.id if spool_obj else None,")
add(indent + "            'start_remain': tray_info.get('remain') if tray_info else None,")
add(indent + "            'start_total_len': tray_info.get('total_len') if tray_info else None,")
add(indent + "            'last_remain': tray_info.get('remain') if tray_info else None,")
add(indent + "            'usages': [],")
add(indent + '        }')
add('')
add(indent + '# LIVE: Slot-Wechsel erkennen und Verbrauch aufsummieren')
add(indent + 'if serial_from_topic and serial_from_topic in active_jobs:')
add(indent + "    info = active_jobs.get(serial_from_topic, {})")
add(indent + "    job_id = info.get('job_id')")
add(indent + '    if job_id:')
add(indent + '        job = session.get(Job, job_id)')
add(indent + '        if job:')
add(indent + "            slot = job_data.get('tray_target') if isinstance(job_data, dict) else None")
add(indent + '            if slot is None:')
add(indent + "                slot = job_data.get('tray_current') if isinstance(job_data, dict) else None")
add(indent + '            current_slot = int(slot) if slot is not None else info.get("slot")')
add(indent + '            if current_slot is not None and info.get("slot") is not None and current_slot != info.get("slot"):')
add(indent + '                tray_prev = _find_tray(ams_data if isinstance(ams_data, list) else [], info.get("slot"))')
add(indent + '                if tray_prev and isinstance(tray_prev, dict):')
add(indent + "                    info['last_remain'] = tray_prev.get('remain')")
add(indent + '                usage = _finalize_current(info)')
add(indent + '                if usage:')
add(indent + "                    info.setdefault('usages', []).append(usage)")
add(indent + '                _set_current_slot(info, current_slot, job)')
add(indent + '            tray_info_now = _find_tray(ams_data if isinstance(ams_data, list) else [], info.get("slot"))')
add(indent + '            if tray_info_now and isinstance(tray_info_now, dict):')
add(indent + "                info['last_remain'] = tray_info_now.get('remain')")
add(indent + '            total_used_mm = 0.0')
add(indent + '            total_used_g = 0.0')
add(indent + "            for u in info.get('usages', []):")
add(indent + '                total_used_mm += u.get("used_mm") or 0.0')
add(indent + '                total_used_g += u.get("used_g") or 0.0')
add(indent + '            if info.get("slot") is not None:')
add(indent + '                sp = session.get(Spool, info.get("spool_id")) if info.get("spool_id") else None')
add(indent + '                used_mm, used_g = _calc_usage(')
add(indent + '                    sp,')
add(indent + '                    info.get("start_remain"),')
add(indent + '                    info.get("last_remain"),')
add(indent + '                    info.get("start_total_len"),')
add(indent + '                )')
add(indent + '                total_used_mm += used_mm')
add(indent + '                total_used_g += used_g')
add(indent + '                if sp and used_g and sp.weight_full is not None:')
add(indent + '                    try:')
add(indent + '                        sp.weight_current = float(sp.weight_full) - used_g')
add(indent + '                        session.add(sp)')
add(indent + '                    except Exception:')
add(indent + '                        pass')
add(indent + '            job.filament_used_mm = total_used_mm')
add(indent + '            job.filament_used_g = total_used_g')
add(indent + '            session.add(job)')
add(indent + '            session.commit()')
add('')
add(indent + '# FINISH: Abschluss & job_spool_usage schreiben')
add(indent + "if gstate.upper() in ('FINISH', 'IDLE', 'COMPLETED') and serial_from_topic and serial_from_topic in active_jobs:")
add(indent + '    info = active_jobs.pop(serial_from_topic, {})')
add(indent + "    job_id = info.get('job_id')")
add(indent + '    if job_id:')
add(indent + '        job = session.get(Job, job_id)')
add(indent + '        if job:')
add(indent + '            tray_final = _find_tray(ams_data if isinstance(ams_data, list) else [], info.get("slot"))')
add(indent + '            if tray_final and isinstance(tray_final, dict):')
add(indent + "                info['last_remain'] = tray_final.get('remain')")
add(indent + '            usage = _finalize_current(info)')
add(indent + '            if usage:')
add(indent + "                info.setdefault('usages', []).append(usage)")
add(indent + '            total_used_mm = sum(u.get("used_mm") or 0.0 for u in info.get("usages", []))')
add(indent + '            total_used_g = sum(u.get("used_g") or 0.0 for u in info.get("usages", []))')
add(indent + '            job.filament_used_mm = total_used_mm')
add(indent + '            job.filament_used_g = total_used_g')
add(indent + '            job.finished_at = datetime.utcnow()')
add(indent + '            if not job.spool_id and info.get("usages"):')
add(indent + '                first_spool = next((u.get("spool_id") for u in info["usages"] if u.get("spool_id")), None)')
add(indent + '                if first_spool:')
add(indent + '                    job.spool_id = first_spool')
add(indent + '            session.add(job)')
add(indent + '            session.exec(sa.delete(JobSpoolUsage).where(JobSpoolUsage.job_id == job.id))')
add(indent + '            order_idx = 0')
add(indent + "            for u in info.get('usages', []):")
add(indent + '                session.add(JobSpoolUsage(')
add(indent + '                    job_id=job.id,')
add(indent + '                    spool_id=u.get("spool_id"),')
add(indent + '                    slot=u.get("slot"),')
add(indent + '                    used_mm=u.get("used_mm") or 0.0,')
add(indent + '                    used_g=u.get("used_g") or 0.0,')
add(indent + '                    order_index=order_idx,')
add(indent + '                ))')
add(indent + '                order_idx += 1')
add(indent + "            touched_spools = set(u.get('spool_id') for u in info.get('usages', []) if u.get('spool_id'))")
add(indent + '            for sid in touched_spools:')
add(indent + '                sp = session.get(Spool, sid)')
add(indent + '                if sp:')
add(indent + '                    sp.used_count = (sp.used_count or 0) + 1')
add(indent + '                    sp.last_slot = info.get("slot")')
add(indent + '                    sp.last_seen = datetime.utcnow().isoformat()')
add(indent + '                    session.add(sp)')
add(indent + '            session.commit()')
block = "\n".join(L) + "\n"
text = text[:start] + block + text[end:]
path.write_text(text, encoding='utf-8')
