"""Add auto_connect to printer

Revision ID: a662aa086a07
Revises: 20231202_add_spool_usage_fields
Create Date: 2025-12-02 22:18:47.051671

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import text


# revision identifiers, used by Alembic.
revision: str = 'a662aa086a07'
down_revision: Union[str, Sequence[str], None] = '20231202_add_spool_usage_fields'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Prüfe, ob die Spalte schon existiert
    conn = op.get_bind()
    result = conn.execute(text("PRAGMA table_info(printer);"))
    columns = [row[1] for row in result]
    if 'auto_connect' not in columns:
        op.add_column('printer', sa.Column('auto_connect', sa.Boolean(), nullable=False, server_default=sa.text('0')))
        print("Spalte 'auto_connect' wurde hinzugefügt.")
    else:
        print("Spalte 'auto_connect' ist bereits vorhanden – Migration übersprungen.")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('spool', 'first_seen',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_column('printer', 'auto_connect')
    # ### end Alembic commands ###
